name: youtube_mirror_viewer
description: YouTube viewer via Piped/Invidious mirrors (Flutter WebView).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
